version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/BlogWebsite?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_PROFILES_ACTIVE=prod

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=BlogWebsite
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: